### ISSUE TITLE
Where do you pull your DeFi data from? 

### ISSUE THREAD

**Issue by pakaplace** [mikemcdonald/mikemcdonald.github.io#1]
Love the chart and hosted site. I was wondering where you pull your DeFi data from if you don't mind answering? Thanks in advance.

**Comment by mikemcdonald** [comment]
Directly from the smart contracts. For some it's calling a single smart contract for the eth balance or weth balance, and for something like uniswap it first queries the list of exchange contracts and then sums the balance. All of queries require a full archive node to retrieve balances at a historical block number
